# Site
repository: luo-mingjie/luo-mingjie
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Ming-Jie LUO
title: TSINGHUA UNIVERISTY · BEIJING, CHINA 100084
email: luomingjie_thu@outlook.com
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
website: luo-mingjie.github.io/luo-mingjie
website_title: Github

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: xxx
github_username:  luo-mingjie
# stackoverflow_username: "00000001"
# dribbble_username: xxx
# facebook_username: xxx
# flickr_username: xxx
# instagram_username: xxx
linkedin_username: mj-luo
# xing_username: xxx
# pinterest_username: xxx
# youtube_username: xxx
# googleplus_username: xxx
# orcid_username: 0000-0001-7482-4975

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  I am an M.D. candidate at School of Medicine, Tsinghua University. Currently, I am doing clinical practicing at Peking Union Medical College Hospital (PUMCH), China. 

  I am interested in translational biomedical research and solving clinical problems using artiﬁcial intelligence. I have been working on computational methods for the identiﬁcation of biomarkers for patients’ responses to anti-cancer reagents. I have developed a screening platform to identify therapeutic targets for treating cancer patients based on the CRISPR/Cas9 technology. I am using data mining strategies to analyze large scale electrical medical records.

  I am expecting to earn my M.D. degree in June 2022, and I am looking for post-doc positions on biomedical research. Alternatively I'm considering taking a career of being a doctor.

content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: left
  #       title: Project name
  #       link: github.com/luo-mingjie
  #       link_text: Link Text
  #       additional_links:
  #         - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #           icon: fab fa-github
  #           url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #         - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #           icon: fab fa-github
  #           url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #       quote: >
  #         Short overview of the project (optional)
  #       description: | # this will include new lines to allow paragraphs
  #         Description about the work on/with the project
  - title: Education
    layout: list
    content:
      - layout: left
        title: Bachelor of Science
        caption: 2014 - 2017
        sub_title: Tsinghua University
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          I spent 3 years at Tsinghua University studying basic science and pre-med courses. I've covered many subjects in mathematics, chemistry and physics, including calculus, linear algebra, probability and statistics, general physics, pharmacology, inorganic, analytical and organic chemistry. I have also involved in many experimental subjects, e.g. biochemistry, cell biology, molecular biology, genetics, neuroscience, etc. Medical courses include anatomy, histology, physiology, pathology, pathophysiology, immunology, microbiology, parasitology, psychology and etc. 

          During my undergraduate, I undertook some projects with Prof. Li Wu and Prof. Xuegong Zhang on immunology and bioinformatics.

          I spent a lot of my free time taking computer science courses and received certificate of **Computer Science and Programming Using Python**.
      - layout: left
        title: Master of Research
        caption: 2017 - 2019
        sub_title: University of Melbourne
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          I previously received an Masters' of Research from University of Melbourne, during which I was fortunate to work with Prof. David Huang from the Department of Cancer and Haematology and Prof. Terry Speed from the Department of Bioinformatics, the Walter and Eliza Hall Institute of Medical Research. My researches focus on translational cancer research, large-scale CRISPR/Cas9 screening, and computational methods for predicting responses for anti-cancer treatments. I received funding support from the National Scholarship Council.
      - layout: left
        title: Doctor of Medicine
        caption: 2019 - 2021
        sub_title: >
          Tsinghua University
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          I previously received an Masters' of Research from University of Melbourne, during which I was fortunate to work with Prof. David Huang from the Department of Cancer and Haematology and Prof. Terry Speed from the Department of Bioinformatics, the Walter and Eliza Hall Institute of Medical Research. My researches focus on translational cancer research, large-scale CRISPR/Cas9 screening, and computational methods for predicting responses for anti-cancer treatments. I received funding support from the National Scholarship Council.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Walter and Eliza Hall Institute of Medical Research (WEHI)
        link: wehi.edu.au
        link_text: wehi.edu.au
        sub_title: Biomedical research
        caption: 2017 - 2019
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          I worked with Prof. David Huang from the Department of Cancer and Haematology and Prof. Terry Speed from the Department of Bioinformatics, the Walter and Eliza Hall Institute of Medical Research. My researches focus on translational cancer research, large-scale CRISPR/Cas9 screening, and computational methods for predicting responses for anti-cancer treatments.

          More explanation……
      - layout: top-middle
        title: Peking Union Medical College Hospital (PUMCH，北京协和医院) 
        link: www.pumch.cn/en/introduction.html
        link_text: pumch.cn
        sub_title: Intern doctor 
        caption: 2019 - Present
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          I am studying clinical medicine and rotating as an intern doctor at the Peking Union Medical College Hospital (PUMCH), China.
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Here is some of my other interests and hobbies are:
      - Swimming
      - Demigods and Semi-Devils (天龙八部) and other fictions by Gum Yoong
      - Photography

      Look at this cool image  
      ![天空一角](/images/old_temple.jpg "old_temple")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
