# Site
repository: luo-mingjie/luo-mingjie
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ming-Jie LUO 罗明杰
title: TSINGHUA UNIVERISTY · BEIJING, CHINA 100084
email: luomingjie_thu@outlook.com
# email_title: Email (Email title override)
website: linkedin.com/in/mj-luo/
website_title: Linkedin
phone: THU_LuoM
phone_title: Wechat
# website: scholar.google.com/citations?hl=en&user=tbBjJHEAAAAJ
# website_title: Google Scholar

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: xxx
github_username:  luo-mingjie
# stackoverflow_username: "00000001"
# dribbble_username: xxx
# facebook_username: xxx
# flickr_username: xxx
# instagram_username: xxx
linkedin_username: mj-luo
# xing_username: xxx
# pinterest_username: xxx
# youtube_username: xxx
# googleplus_username: xxx
# orcid_username: 0000-0001-7482-4975

# Additional icon links
additional_links:
- title: Google Scholar
  icon: fas fa-graduation-cap
  url: https://scholar.google.com/citations?hl=en&user=tbBjJHEAAAAJ
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)


# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  I am an M.D. candidate at School of Medicine, Tsinghua University. Currently, I am doing clinical practice at Peking Union Medical College Hospital (PUMCH), China.

  I am interested in translational biomedical research and solving clinical problems using artiﬁcial intelligence. I have worked on computational methods for the identiﬁcation of biomarkers for patients’ responses to anti-cancer reagents. I have developed a screening platform to identify therapeutic targets for treating cancer patients based on the CRISPR/Cas9 technology. Recently, I have been using data mining strategies to analyze large scale electrical medical records.

  I am expecting to earn my M.D. degree in June 2022, and I am looking for doctor positions in oncology. Alternatively, I’m considering taking post-doc positions in translational biomedical research.
content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: left
  #       title: Project name
  #       link: github.com/luo-mingjie
  #       link_text: Link Text
  #       additional_links:
  #         - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #           icon: fab fa-github
  #           url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #         - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #           icon: fab fa-github
  #           url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #       quote: >
  #         Short overview of the project (optional)
  #       description: | # this will include new lines to allow paragraphs
  #         Description about the work on/with the project
  - title: Education
    layout: list
    content:
      - layout: left
        title: Bachelor of Science
        caption: 2014 - 2017
        sub_title: Tsinghua University
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          I spent 3 years at Tsinghua University studying basic science and pre-med courses. I’ve covered many mathematics, chemistry, and physics subjects, including calculus, linear algebra, probability and statistics, general physics, pharmacology, inorganic, analytical and organic chemistry. I also had many experimental subjects, e.g., biochemistry, cell biology, molecular biology, genetics, neuroscience, etc. Medical courses I took included anatomy, histology, physiology, pathology, pathophysiology, immunology, microbiology, parasitology, psychology, etc.

          During my undergraduate, I undertook some projects with Prof. Li Wu and Prof. Xuegong Zhang on immunology and bioinformatics.

          I spent a lot of my free time taking computer science courses and received some certificates of Computer Science.
      - layout: left
        title: Master of Research
        caption: 2017 - 2019
        sub_title: University of Melbourne
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          I previously received an Masters' of Research from University of Melbourne, during which I was fortunate to work with Prof. David Huang from the Department of Cancer and Haematology and Prof. Terry Speed from the Department of Bioinformatics, the Walter and Eliza Hall Institute of Medical Research. My researches focus on translational cancer research, large-scale CRISPR/Cas9 screening, and computational methods for predicting responses for anti-cancer treatments. I received funding support from the National Scholarship Council.
      - layout: left
        title: Doctor of Medicine
        caption: 2019 - 2021
        sub_title: |
          Tsinghua University

          & Peking Union Medical College Hospital (PUMCH，北京协和医院)           
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          I am studying clinical medicine and rotating as an intern doctor at the Peking Union Medical College Hospital (PUMCH), China.

          At the same time, I have collaborated with several professors at the Chinese Academy of Medical Sciences & PUMCH, including: Prof. Jingnan Li in Gastroenterology, approaches for gut microbiomic profile analysis; Prof. Xin You in Rheumatology, exploring flora transplantation with metabolomic and gut microbiomic approaches for patients with autism; Dr. Chong Wei in Hematology: transcriptome analysis for immunotherapy of leukemia; Dr. Jia-Nan Gong in Animal Research Institute: targeted therapeutic approaches for various solid tumors (gastric cancer, colorectal cancer, etc.).
  - title: Selected Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Intern doctor 
        link: www.pumch.cn/en/introduction.html
        link_text: pumch.cn
        sub_title: Peking Union Medical College Hospital (PUMCH，北京协和医院) 
        caption: 2019 - Present
        description: | # this will include new lines to allow paragraphs
          I am studying clinical medicine and rotating as an intern doctor at the Peking Union Medical College Hospital (PUMCH), China.

          The program includes clinical courses (e.g. diagnostics, internal and external medicine, neurology, obstetrics and gynecology) and internship rotations in all major departments at PUMCH.
      - layout: top-middle
        title: Advancing BH3 mimetics for treating cancers
        # link: wehi.edu.au
        # link_text: wehi.edu.au
        # sub_title: Walter and Eliza Hall Institute of Medical Research (WEHI)
        caption: 2017 - 2019
        description: | # this will include new lines to allow paragraphs
          We identiﬁed two BCL2 relatives as the most important survival factors for the colorectal cancer (CRC). We also validated them as potential targets by pharmacological inhibition in both in vivo models and patient-derived organoids. We have published an abstract at the 2018 EMBL Australia Postgraduate Symposium (EAPS18). I presented this work as one of the keynote speakers EAPS18. This work is published in Cell Death and Disease (IF=6).
      - layout: top-middle
        title: Predicting responses to BH3 mimetic compounds using transcriptional proﬁles
        # link: wehi.edu.au
        # link_text: wehi.edu.au
        # sub_title: Walter and Eliza Hall Institute of Medical Research (WEHI)
        caption: 2018 - 2019
        description: | # this will include new lines to allow paragraphs
          I have developed computational models for predicting the sensitivity of BH3 mimetics and other anticancer therapies based on molecular proﬁles (e.g. transcriptomics). Additionally this model has shown potential in identifying biomarkers which might be related to the biological mechanisms of the drugs. I have presented this work as an oral poster presentation at the Melbourne Health Young Investigators Research Symposium 2019.
      - layout: top-middle
        title: Identifying regulators of pro-survival factors by CRISPR/Cas9 screening
        # link: wehi.edu.au
        # link_text: wehi.edu.au
        # sub_title: Walter and Eliza Hall Institute of Medical Research (WEHI)
        caption: 2018 - 2019
        description: | # this will include new lines to allow paragraphs
          BCL2 and its relatives have been implicated to play a crucial role to maintain the survival of various malignances. To identify therapeutic targets that can be utilized to inhibit BCL2 and its relatives, we optimize a genome-wide clustered regularly interspaced short palindromic repeats (CRISPR) screening platform and use it to identify genetic vulnerabilities in cancer cells. We have identiﬁed several candidate genes. I have ﬁnished this work for a section in my M.Res. thesis.
      - layout: top-middle
        title: Structural analysis of MRJP1 protein
        # link: wehi.edu.au
        # link_text: wehi.edu.au
        # sub_title: Walter and Eliza Hall Institute of Medical Research (WEHI)
        caption: 2017
        description: | # this will include new lines to allow paragraphs
          Based on the research prospects of major royal jelly protein1 (MRJP1), we focused on using biochemical and biophysical methods to study its spatial structure and its stability and explored its protective eﬀect on the degeneration process of cataract-causing crystal proteins. We published an abstract based on this work at the 13th National Enzymology Symposium.
      - layout: top-middle
        title: "SuvCas9: a surveillance system for monitoring carcinogenesis"
        # link: wehi.edu.au
        # link_text: wehi.edu.au
        sub_title: Gold medal at iGEM
        caption: 2016
        description: | # this will include new lines to allow paragraphs
          We constructed a suvCas9 system in S. cerevisiae to function as the monitor of genomic sequence. The system has the potential to prevent carcinogenesis by killing all the mutated cells. We won a gold medal for this project at iGEM (International Genetically Engineered Machine competition).
  - title: BIOINFORMATICS AND DATA SCIENCE
    layout: text
    content: |
      I have been working intensively on projects requiring both wet-lab and bioinformatics skills. I am familiar with data mining on large scale biomedical databases, such as The Cancer Genome Atlas (TCGA). I have experience working with NGS data including single cell sequencing, RNA seq, Chipseq, ATAC seq, microbiome data and etc. I have taught Bioinformatics Workshops at the NJU(Nanjing University)-WEHI Symposium 2018.

      My skills:
      - **Programming languages**: R, bash, python and matlab
      - **Data-mining**: large scale biomedical resources, web scraper
      - **Mathematical modeling**: classical statistics, ODE modelling, machine learning methods

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Here is some of my other interests and hobbies are:
      - Swimming
      - Demigods and Semi-Devils (天龙八部) and other fictions by Gum Yoong
      - Photography

      My wechat
      ![wechat](images/wechat.jpg "wechat")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
